version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-infra_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-infra_pass}
      POSTGRES_DB: ${POSTGRES_DB:-infra_monitor}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-infra_user}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  web:
    build: .
    env_file:
      - .env
    command: bash -c "python /app/infra_monitor/manage.py migrate && python /app/infra_monitor/manage.py collectstatic --noinput && python /app/infra_monitor/manage.py seed_demo && gunicorn infra_monitor.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    env_file:
      - .env
    command: bash -c "cd /app/infra_monitor && celery -A infra_monitor worker -l info"
    volumes:
      - .:/app
    depends_on:
      - web

  beat:
    build: .
    env_file:
      - .env
    command: bash -c "cd /app/infra_monitor && celery -A infra_monitor beat -l info"
    volumes:
      - .:/app
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
